### PR TITLE
adding globals for CombatTracker

### PR DESCRIPTION
**Pull request by modhunter**

### CODE REVIEW

**Comment by MrTheSoulz** [comment]
You dont need these, fo you?
You can call them thru the conditions, NeP.DSL:Get('ttd')(unit).

Going this way allows me tto change things without breaking stuff in the future.

**Comment by modhunter** [comment]
I need to access the LastCast value inside a custom function (e.g.):

`local LastCast = NeP.CombatTracker:LastCast('player')`

DSL lastcast only gives me true or false which won't work for what I need to do:
```
NeP.DSL:Register("lastcast", function(Unit, Spell)
	spell = NeP.Spells:Convert(Spell)
	if UnitIsUnit('player', Unit) then
		return NeP.LastCast == spell
	end
	return NeP.CombatTracker:LastCast(Unit) == spell
end)
```

**Comment by MrTheSoulz** [comment]
```local bool, spell = NeP.CombatTracker:LastCast('player')````

**Comment by modhunter** [comment]
not needed anymore, thanks!

**Pull request closed without merging**
